### ISSUE TITLE
Use monospace font in registry editor

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#100]

**Comment by joshm-3b6b58** [comment]
For just folders labels, key names and values? or like the UI stuff to?

**Comment by DanielSank** [comment]
For key names and values, please.

**Comment by joshm-3b6b58** [comment]
OK I'll do this tomorrow. Do you like this:
https://www.google.com/fonts/specimen/Roboto+Mono
?

it should match the other fonts already in the application

**Comment by DanielSank** [comment]
sure
