### ISSUE TITLE
Grapher: Add search tool for datasets

### ISSUE THREAD

**Issue by JulianSKelly** [labrad/scalabrad-web#105]
because this would be dope af

**Comment by DanielSank** [comment]
+100.

For the hapless Martinis group user trying to search the datavault in the meanwhile, note the existence of `pyle/scripts/dvgrep.py`.

**Comment by joshm-3b6b58** [comment]
@JulianSKelly can you detail some how you think this would look. Search by parameters, keyword? titles?

**Comment by JulianSKelly** [comment]
I think all of those things would be good. Titles at an absolute minimum would be a huge gain over what we have now, and searching by parameters would also be super useful. Also, search by e.g. measure.

**Comment by DanielSank** [comment]
One definitely wants to be able to have some combination of dates and dataset names, i.e. "Where is that foobar experiment I did some time a few days ago?" We tend to structure our data vault directories by date, so one could use a range of directories to search and give some keywords or title.
