### ISSUE TITLE
How is eclipse supposed to work here?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#108]
If I run sbt in the project rot and then do `> eclipse`, sbt tells me that it's generating eclipse project files. However, I don't see any new project files anywhere. What gives?

**Comment by joshm-3b6b58** [comment]
I never did anything special in sbt i don't think. I just opened the repo in eclipse. 

I find eclipse to be very antagonizing to get setup in general.

**Comment by maffoo** [comment]
This repo is organized as several subprojects in the `server/`, `client-js/` and `jsonrpc/` folders. When you run the `eclipse` task, sbt generates eclipse projects in those directories. In eclipse, go to the `File >> Import...` menu and under the `General` category chose `Existing Projects into Workspace`. This will bring up a dialog; browse to the directory where you've checked out scalabrad-web and it will search all subfolders for eclipse project files and should find all three projects which you can then import all at once.

**Comment by DanielSank** [comment]
Thanks, it found jsonrpc and the server, but not clientjs. Also, with those projects imported, eclipse marks an error at every reference to `JsonRpc`. Tried cleaning and rebuilding but the problem persists.

**Comment by maffoo** [comment]
Oh right, the client-js folder doesn't have any scala, so sbt sort of ignores it. What I usually do is create a new project (of type `General >> Project`), give it a name like `scalabrad-web-client-js` to match the generated project names, and then override the location to point to the client-js folder. Then you can at least browse and edit files. There are some instructions on google drive about setting up eclipse like installing a typescript plugin.

As for the `JsonRpc` issue, what is the actual error? One thing you should check is look at the java build path for the server project and make sure the scalabrad-web-jsonrpc project is included as a dependency.
