### ISSUE TITLE
Unable to log in production mode

### ISSUE THREAD

**Issue by ckometter** [labrad/scalabrad-web#110]
When I try to run it on production mode I get the following warning: warn - application logger configu"ration in conf files is deprecated and has no effect. Use a logback configuration file instead."
And when I try to login, it doesn't accept the labrad password. I'm using windows 7

**Comment by joshm-3b6b58** [comment]
Does it work in dev mode?

**Comment by ckometter** [comment]
Hi,
I figured it out. Pressing enter doesn't work, you have to click the login button. I was using the pre-build binary package.

**Comment by DanielSank** [comment]
Yeah that got fixed recently.
