### ISSUE TITLE
Grapher: Add ability to plot one or some of dependent variables

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#116]
Right now, there is no ability to plot only selected dependent variables. It would be nice if one could select to plot only one or only a selected set of dependent variables (as was possible with the Delphi Grapher).

**Comment by joshm-3b6b58** [comment]
Fixed https://github.com/labrad/scalabrad-web/pull/176

**Comment by jwenner** [comment]
@joshmutus, this doesn't seem to be fixed with the version on matrix-reloaded. Does this mean we should bump the version number and deploy?
