### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#118]
Would it be possible to bump the version number at some point and do a release to Bintray? Or would it be better to wait until #101 and #109 are merged in? Some of us are using the web interface in production mode and so are unable to use some of the goodies (such as the live view) added since 1.0.0-M2. Thanks @maffoo or @joshmutus.

**Comment by maffoo** [comment]
Just pushed version 1.0.0-M3 to bintray.
