### ISSUE TITLE
Grapher: 1D zooming can flip data upside down

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#119]
When zooming into a 1D plot by drawing the zoom rectangle from the top going to the bottom, the resulting plot will be flipped upside down relative to the original plot. Hence, a dip will turn into a peak. Using version 1.0.0-M3.

**Comment by maffoo** [comment]
@jwenner, I'm unable to reproduce locally. Can you give any more details?

**Comment by maffoo** [comment]
Ok, I think I see the problem; we're using Array.sort to order the x and y limits, but this actually converts numbers to strings before sorting, so sometimes the x or y axis can get flipped. Javascript, you crazy! (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)
