### ISSUE TITLE
reg.copyDir returns to early when copying a folder of folders

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#124]
When copying a large directory of keys, the `await registry.copyDir` will wait until the whole folder is copied to return. However when copying a folder of folders, it will return after the first folder is copied. This causes some confusion because the folder will appear to be copied, when the folders contained therein aren't copied yet.

**Comment by maffoo** [comment]
I'm not able to reproduce this issue exactly, but I've fixed up the directory copy logic in #128 and that may help here as well.

**Comment by joshm-3b6b58** [comment]
It only happens to me when I have a folder that contains a subfolder with a
lot of keys that takes a while to copy. I'll see if the latest PR fixes
this.
