### ISSUE TITLE
Do we need to require documentation in the code?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#13]
I'm having a little bit of a hard time reviewing #11 because I don't know the intent of the code. Do we need some basic requirements on inline documentation in this project?

**Comment by maffoo** [comment]
The comments could certainly be improved. Google javascript style guide says use jsdoc (http://google.github.io/styleguide/javascriptguide.xml#Comments) but we are using typescript, so some of what's there is redundant with the ts types.

**Comment by DanielSank** [comment]
Yeah, the annotations seem unnecessary. We should at least use the textual descriptions though.
