### ISSUE TITLE
Indicate starred datasets

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#130]
This is a really useful feature in the Delphi grapher. It makes finding relevant datasets much easier/possible.

**Comment by DanielSank** [comment]
@maffoo we can close this, yes? Not sure why it didn't auto-close.

**Comment by maffoo** [comment]
This isn't merged to master yet. I deployed to matrix-reloaded to have people test it out. If you'd like to review, I can put up a PR. At the moment it's on a branch with a bunch of other changes, and I don't have time right now to clean things up, but you could still look at the changes one at a time at least.

**Comment by DanielSank** [comment]
I think my response to that depends on your estimated short term availability, which I would guess is pretty low. Thoughts?

**Comment by maffoo** [comment]
Yes, I'm going to be sporadic at best for this next week. I'll be back on the 25th, we can discuss then.
