### ISSUE TITLE
The new key window is so small that you can't see all the fields, or the buttons

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#132]

**Comment by joshm-3b6b58** [comment]
I think this is the same as issue #97 correct? This happens sporadically to me for all the dialogs. I usually have to change the zoom level. Also restarting Chrome fixes it. I have no idea what the problem is here, I've tried reaching out to the polymer dev team, but haven't heard back :/

**Comment by DanielSank** [comment]
In my head it was different because this is for new keys and #97 is for editing, but since they're probably the same underlying issue let's close this.
