### ISSUE TITLE
Eclipse thinks these projects have errors

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#133]
If I clone the repo and do this

```
$ cd ~/src/scalabrad-web/jsonrpc
$ sbt
> compile
```

I get a bunch of compiler errors

if I

```
$ cd ..
$ sbt compile
```

Then it works. The annoying part is that within eclipse, both scalabrad-web-jsonrpc and scalabrad-web-server are marked as having errors (although I don't know how to tell eclipse to tell me _what_ the errors are.

**Comment by maffoo** [comment]
There are two parts here. First, re sbt project structure, when you run the `sbt` command it looks in the current directory for a build.sbt file. Since that's defined at the repo root, not in the `jsonrpc/` subdirectory, you have to run sbt from the repo root. Once you're in sbt, you can switch to a particular project and then run commands in that project only:

```
$ sbt
...
[info] Set current project to scalabrad-web (in build file:/Users/maffoo/src/scalabrad-web/)
> project jsonrpc
[info] Set current project to scalabrad-web-jsonrpc (in build file:/Users/maffoo/src/scalabrad-web/)
> compile
[success] Total time: 0 s, completed Jan 17, 2016 7:01:41 AM
```

Alternately, you can run sbt commands for particular projects by prefixing them with the project name:

```
> jsonrpc/compile
[success] Total time: 0 s, completed Jan 17, 2016 7:03:11 AM
```

To see a list of all sbt subprojects, run `projects`, and to see which project you're currently in, run `project`.

Now, to the question about eclipse, go to the main menu and select `Window >> Show View >> Problems`. This should bring up a window showing the reasons why eclipse is complaining. You can filter to see only problems with the current project, then open a file from the project you're worried about to make sure it's selected as the current project. Hopefully this should give some info about what's going wrong. You may need to regenerate the project files in sbt, then refresh in eclipse, or maybe it just needs a clean rebuild in Eclipse.

**Comment by DanielSank** [comment]
Taking it from the top

```
$ git clone path/to/this/repo/scalabrad-web.git
$ cd scalabrad-web
$ sbt eclipse
<stuff happens>
```

In eclipse, `file>>Import...>>Existing projects into workspace>>~/src/scalabrad-web`. In other words, I choose the root directory of the git repository. After selecting this, eclipse shows two projects checked:

`/home/danielsank/src/scalabrad-web/jsonrpc`
`/home/danielsank/src/scalabrad-web/server`

I hit `Finish`. Here are the errors.

```
Description Resource    Path    Location    Type
missing or invalid dependency detected while loading class file 'DefaultReads.class'. Could not access type Instant in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultReads.class' was compiled against an incompatible version of java.time. scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultReads.class'. Could not access type LocalDate in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultReads.class' was compiled against an incompatible version of java.time.   scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultReads.class'. Could not access type LocalDateTime in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultReads.class' was compiled against an incompatible version of java.time.   scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultReads.class'. Could not access type ZonedDateTime in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultReads.class' was compiled against an incompatible version of java.time.   scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultWrites.class'. Could not access type Instant in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultWrites.class' was compiled against an incompatible version of java.time.   scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultWrites.class'. Could not access type LocalDate in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultWrites.class' was compiled against an incompatible version of java.time. scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultWrites.class'. Could not access type LocalDateTime in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultWrites.class' was compiled against an incompatible version of java.time. scalabrad-web-jsonrpc       Unknown Scala Problem
missing or invalid dependency detected while loading class file 'DefaultWrites.class'. Could not access type ZonedDateTime in value java.time, because it (or its dependencies) are missing. Check your build definition for missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.) A full rebuild may help if 'DefaultWrites.class' was compiled against an incompatible version of java.time. scalabrad-web-jsonrpc       Unknown Scala Problem
Project scalabrad-web-server macros not built due to errors in dependent project(s) scalabrad-web-jsonrpc   scalabrad-web-server        Unknown Scala Problem
Project scalabrad-web-server main not built due to errors in dependent project(s) scalabrad-web-jsonrpc scalabrad-web-server        Unknown Scala Problem
Project scalabrad-web-server tests not built due to errors in dependent project(s) scalabrad-web-jsonrpc    scalabrad-web-server        Unknown Scala Problem
scalabrad-web-jsonrpc's tests not built due to errors in dependent scope(s) main    scalabrad-web-jsonrpc       Unknown Scala Problem
```

Is this a problem with JDK versions? I think I'm using 8.0_51.

**Comment by maffoo** [comment]
Be sure to tell eclipse to use the appropriate JDK versions. That setting is independent of what you're using on the system outside of eclipse.

**Comment by DanielSank** [comment]
I tried putting java8 first on my `PATH` and then invoking eclipse from the command line. That doesn't seem to have done it.

**Comment by maffoo** [comment]
I was trying to say in my previous comment that this has nothing to do with external system settings like your path. Inside eclipse, go to the preferences and look for `Java >> Installed JREs`. Make sure there's a JDK 8 in the list and I would probably just set it to be the default. Then you can check in the project settings for the jsonrpc project. It should just use the eclipse default JRE, but you can override this per project if desired.

**Comment by DanielSank** [comment]
Nice, that worked. For any other readers who run into this problem:

My system has a jre7 at `/usr/lib/jvm/java-7-openjdk-amd64`, but I had later put a jre8 in `~/lib/`. I figured the problem was that I was running eclipse and letting it find the v7 jre. I thought that if I explicitly put the jre8 on `PATH` while running eclipse, then eclipse would use the right jre. Not the case. At @maffoo said, if you go to `window>>Preferences` and then find `Java/Installed JREs` you'll see that eclipse has the full path the the pre-existing jre7 selected. You can add whatever other jre you want there.

Thanks @maffoo.
