### ISSUE TITLE
Sub-list of servers for the node browser

### ISSUE THREAD

**Issue by thchwhite** [labrad/scalabrad-web#143]
There should be a way to create a custom sub-list of servers so one doesn't have to look through every server to find the ones you want.  This is especially relevant for the ADR's where most of the servers are unused.

**Comment by maffoo** [comment]
One thing you should know about is the node now lets you set a list of servers that will be autostarted. The web UI doesn't currently support this, but if you just use the python client you will see a bunch of `autostart_*` settings that you can use to set up the list, and then just call `node.autostart()` to run them all. This will avoid having to go through the web interface at all.

Of course, having the web UI support this in some way will be nice. Basically, this you could add and remove servers from the autostart list, and start all of them with one button.

**Comment by joshm-3b6b58** [comment]
Also, adding the filter/search dialog to the node browser would help this in the meantime.

**Comment by joshm-3b6b58** [comment]
@thchwhite did you manage to find a workaround for this? Is this still an issue?

**Comment by joshm-3b6b58** [comment]
@thchwhite is this still a problem?

**Comment by thchwhite** [comment]
Yeah.  I thought I found a solution using symlinks, but it was super unstable.  I like the idea of the auto-start list, but often you need to restart just one server several times, and its still a pain to find.  Ideally you could have an option to only display the auto-start list.  Like how you can click a button on the old grapher to only display stared data sets.

**Comment by jwenner** [comment]
Should this be moved to milestone v2.1, as I believe this goes beyond feature-equivalence with the old Delphi+Java node webpage system?

**Comment by adamcw** [comment]
I'm personally inclined to resolve all the `PE-fixit` milestone items first. For a few reasons:
1. None of the remaining items are that difficult.
2. There are only two of them without `pr-pending` labels
3. I don't like the slippery slope of meeting milestone targets by simply reclassifying them.

On that note though, thanks for all your efforts in helping triage and classify these issues, it's a big help!

**Comment by adamcw** [comment]
How do we envisage this feature working? I can implement a starring system, like the Grapher, but that's going to be Scalabrad-web wide. If a server is important to one person, is it important to everyone, or are people going to each want their own subset?

If we need multiple subsets for various use cases, then we probably want something more like a tag system, where you can then filter by tag.

Search/filter was mentioned. Would that just be an interim solution, or might that actually solve this problem more elegantly than a bunch of tags?

@thchwhite @maffoo @joshmutus

**Comment by maffoo** [comment]
I think we should use the node autostart list for this.
- Add a visual indication by each server of whether it is in the autostart list.
- Add a way to add or remove servers from the autostart list (for example, the indicator could be a star that works like a toggle button to add or remove that server when clicked).
- Add a button to send an autostart command to the node (this could live next to the existing refresh button that reloads the server config).
- Provide a way to filter the list to only show servers that are in the autostart list on _some_ node (they may not be in the autostart list on every node, but that's ok). Again, could just be a toggle button.

I think this would achieve most of what we want without too much work.

**Comment by adamcw** [comment]
This was implemented as suggested by @maffoo due to no other feedback/suggestions.
