### ISSUE TITLE
Yellow traces are difficult to see

### ISSUE THREAD

**Issue by JulianSKelly** [labrad/scalabrad-web#145]
![screen shot 2016-02-08 at 9 56 00 am](https://cloud.githubusercontent.com/assets/8152707/12894196/3c91ebbe-ce4a-11e5-8b14-db57a4f7e050.png)

**Comment by adamcw** [comment]
With the white background and the darker yellow that seems to be in use compared to this screenshot, can we consider this resolved? Else, I can change the yellow to a more orange color if people would prefer. 

I would also perhaps recommend instead using colors that are more appropriate for color-blind users if we are already in the process of altering the colors:

http://mkweb.bcgsc.ca/biovis2012/

![Color Blind Palette](http://mkweb.bcgsc.ca/biovis2012/color-blindness-palette.png)

**Comment by joshm-3b6b58** [comment]
I think we should make the line weight a little thicker as well.
