### ISSUE TITLE
Going from grapher to menu - Star/trash above menu

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#148]
When I am on the grapher page and switch to the menu, the star and trash icons stay on top of the menu. This partially hides the "Manager" option.

Note: Refers to branch operating on matrix-reloaded

**Comment by joshm-3b6b58** [comment]
@maffoo @jwenner 
I think I've fixed this here https://github.com/labrad/scalabrad-web/commit/69154baa5d2150a4eec3e69db7e809199a94cb52 but it's branch off of the maffoo/dev PR. I have insufficient gitfu to know where to go from here. I can continue to review the dev PR and then submit a PR once that's merged?

**Comment by jwenner** [comment]
I think you can do a PR onto the `u/maffoo/dev` branch (e.g., martinisgroup/pyle#869). Right, @maffoo?

**Comment by maffoo** [comment]
Fixed with #161 and deployed
