### ISSUE TITLE
something is broken

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#15]
I've just pulled and tried to run from the master branch but the content of the sub-pages won't render. There's nothing in the manager or registry. I can however access the manager from the ipython shell. 

Maybe I've just done something dumb with git? 
when I `$ git pull` I'm told I'm `Already up-to-date.` and I've checked out the master branch. I've restarted the manager and re compiled the server as per the instructions. 

In the browser console I'm getting the following error:

`WebSocket connection to 'ws://localhost:9000/api/socket2' failed: Error during WebSocket handshake: Unexpected response code: 404`

So it's something on the server side. The server seems to compile without error. Any ideas?

**Comment by maffoo** [comment]
The url should be `ws://localhost:9000/api/socket`. Probably just need to hard refresh the browser (e.g. ctrl+shift+r instead of just ctrl+r). Might want to run `gulp clean` as well just to make sure you don't have any old client-side code hanging out and you get a clean compile.

**Comment by joshm-3b6b58** [comment]
So, hard refresh on the browser didn't help. I ran `$ gulp clean` then `$ gulp serve` now I'm getting an error in the console that seems like total nonsense:

```
Uncaught SyntaxError: Unexpected token <                                                app.js:1
```

**Comment by joshm-3b6b58** [comment]
The console for the client websever says:

```
request for /scripts/app.js rewritten to /index.html
```

is this what we expect?

**Comment by maffoo** [comment]
No, that's not expected. `/scripts/app.js` should get served normally, because there's a file matching that path. I just checked out master, ran `gulp clean` and `gulp serve` and things work for me, so there must be something else different between our environments. Are your npm packages up to date?

**Comment by maffoo** [comment]
Turned out to be a typescript compilation issue; had to run `tsd reinstall` to pull down typescript library definition files, and then compilation succeeded and things worked. Error messages in the `gulp serve` output are not very clear; we should fix this.
