### ISSUE TITLE
Registry: Edit key upon clicking anywhere on value

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#155]
It would be nice if a registry key could be edited by clicking anywhere on the value instead of only after the value. This would be particularly useful if the window is narrowed or there are keys with long entries.

**Comment by joshm-3b6b58** [comment]
Agreed. Also you can click just left of the value as well. That should always work

**Comment by adamcw** [comment]
@joshmutus @jwenner @maffoo Did Pull #192 also fix this issue?

**Comment by jwenner** [comment]
Can't tell. I'm strictly a Windows 7 user, so running the dev version is an open question (#48). The only way I can provide feedback is if someone either makes available a compiled version or loads a version on matrix-reloaded. Speaking of which, the main version on matrix-reloaded doesn't even have 7b4f8a675000ab3759535b07df1d1985c5ab5c0f or any of the later changes, while the /dev/maffoo version is only on 0c80392.

**Comment by jwenner** [comment]
Looks like this is now fixed (at least as of 280f46b), so closing.
