### ISSUE TITLE
how to setup scalabrad-web properly

### ISSUE THREAD

**Issue by ypzhong** [labrad/scalabrad-web#159]
Hi,
    I just installed scalabrad manager and scalabrad-web, pylabrad, and launched them without getting any error. I run python -m labrad.node, I then access localhost:7667 in the browser, but there is nothing there, it's blank. And I got no error message. Is there any pre-configuration I need to setup before launching scalabrad-web? Thanks.

**Comment by maffoo** [comment]
Hi Youpeng!

What version are you running; was it a binary from bintray? Was there any console output from the scalabrad-web server process? Also, what web browser are you using? We've really only tested on up-to-date versions of google chrome, and as much as we'd like to support other browsers, it's not a real high priority right at the moment (see #93).

I should also say that if you got a bintray version those are currently using the play framework, but we plan to change that to use a different server library in the near future (see #151). This will make it easier to setup the web interface using environment variables and/or command line parameters like we do for the manager as well.

**Comment by ypzhong** [comment]
Hi Matthew,
Yes I used the binary version and used Firefox browser. I didn't see any output in the scalabrad-web console. I will try it on chrome and see if this problem can be solved. Thank you very much!

**Comment by ypzhong** [comment]
Hi Matthew,
Yes I used the binary version and used Firefox browser. I didn't see any output in the scalabrad-web console. I will try it on chrome and see if this problem can be solved. Thank you very much!
