### ISSUE TITLE
My suggestion for favicon

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#167]
Since it's called LabRAD, and involves science and experiment, how about a LabRADor in the vein of the "I have no idea what I'm doing dog"
![image](https://cloud.githubusercontent.com/assets/8173925/13971917/50226b80-f051-11e5-9983-e4ab9c11d7e9.png)
So I pasted together some clipart to create the following:
![image](https://cloud.githubusercontent.com/assets/8173925/13971924/5b1297f4-f051-11e5-94de-a5cce90cc11d.png)

The internet tells me that 256x256 is a fine size for a chrome favicon, and I want to believe that :)

Here's how it looks as 32x32. Lines probably need thickening up. I can play with it if anybody likes it
![image](https://cloud.githubusercontent.com/assets/8173925/14001601/11ea92e4-f104-11e5-8cfb-10d9e047e266.png)

**Comment by jwenner** [comment]
I like the general idea. A few nitpicks:
1. When seen as a favicon (in Firefox), the nose/mouth combination looks like a gray blur. Perhaps some coloring would be good? (red tongue, brown labrador). Note with color, you could remove the outline.
2. As a favicon, I can't see the base of the glasses. I can only see the top (looks like a visor!). Perhaps color the glasses differently than the labrador?

**Comment by jwenner** [comment]
FYI, W3C (WWW standards organization) says to use 16x16 or 32x32 and 8- or 16-bit color. https://www.w3.org/2005/10/howto-favicon

**Comment by joshm-3b6b58** [comment]
Good suggestions Jim. I wanted to see if people liked the idea before investing time in actually playing with it.

**Comment by DanielSank** [comment]
bump.

This is really important :P

**Comment by adamcw** [comment]
Seems like as good an idea for a favicon as any!

**Comment by adamcw** [comment]
We clearly can't have Version 2.0 without a favicon. Priority Zero.

**Comment by maffoo** [comment]
I'm personally partial to the LR favicon that we have currently, but I made it so I'm biased...

(I did not spend much time on it, clearly, so I'm not _that_ attached to it :-) )

**Comment by adamcw** [comment]
[This?](https://raw.githubusercontent.com/labrad/scalabrad-web/master/client-js/app/favicon.ico)

**Comment by maffoo** [comment]
No, [this](https://github.com/labrad/scalabrad-web/blob/master/client-js/app/images/labrad.png) (it's what shows up as the favicon now when you browse to any of the deployed web interfaces).

**Comment by adamcw** [comment]
Reminds me of the MSDOS logo, I like it.

**Comment by adamcw** [comment]
I've closed this issue as we already have a favicon and there doesn't seem movement or priority to update it any time soon.
