### ISSUE TITLE
App deletes keys with similar names by accident! 

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#173]
Steps to reproduce:
1. Create a key called `new` and 
2. copy it to a new key called `new_2` 
3. Select and delete `new_2` using the web interface
4. Both `new` and `new_2` are gone!

**Comment by joshm-3b6b58** [comment]
OK, well now I seem to be unable to recreate this...

**Comment by maffoo** [comment]
I'm also unable to reproduce. Can we close?

**Comment by joshm-3b6b58** [comment]
Yes
