### ISSUE TITLE
Error @ bower install

### ISSUE THREAD

**Issue by aanbuvenkatesh** [labrad/scalabrad-web#174]
## for $bower install

$bower install
bower polymer#^1.0.3        not-cached git://github.com/polymer/polymer.git#^1.0.3
bower polymer#^1.0.3           resolve git://github.com/polymer/polymer.git#^1.0.3
bower polymer#^1.0.3           ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/polymer/polymer.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.131]: errno=No error

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=No error
## for $ bower-installer

for $ bower-installer
Setting up install paths...Finished
Running bower install...Error
{ [Error: Failed to execute "git ls-remote --tags --heads git://github.com/polymer/polymer.git", exit code of #128]
  code: 'ECMDERR',
  details: 'fatal: unable to connect to github.com:\ngithub.com[0: 192.30.252.128]: errno=No error\n\n',
  exitCode: 128,
  data:
   { endpoint: { name: 'polymer', source: 'polymer/polymer', target: '^1.0.3' },
     resolver:
      { name: 'polymer',
        source: 'git://github.com/polymer/polymer.git',
        target: '^1.0.3' } } }

**Comment by maffoo** [comment]
Looks like some kind of transient error with github's service or a network problem. Can you get to github from a browser? Can you connect to github via ssh (as described [here](https://help.github.com/articles/testing-your-ssh-connection/))? I'd suggest just trying again, but in any case I don't think this is actually a problem with scalabrad-web.

**Comment by aanbuvenkatesh** [comment]
yes, i'm able to open github from browser. I'm new to github. i've signed up, just before 2 days. so guide me where should i post this to get a resolution.

**Comment by maffoo** [comment]
Can you run the git command in a shell that the error log says is failing (`git ls-remote --tags --heads git://github.com/polymer/polymer.git`)?

**Comment by aanbuvenkatesh** [comment]
Anbu@hp-anbu MINGW64 /d/polymer/polymer-project
$ git ls-remote --tags --heads git://github.com/polymer/polymer.git
35ea8363e6bbed97c95ca951a6ec8c629223dde8        refs/heads/0.5.x
1aff5e214bf539e965b6b52bec08a2fbe69a98ba        refs/heads/0.8-preview
a395ec93ff5e43e0e4308ec8c0c5ba7239f6a13e        refs/heads/1757-kschaaf-negate-2way
0b27b01d268ee6337a8509bf3a97731554be9faf        refs/heads/1913-kschaaf-uniquify
9b8c99346d4337fd9e685551cef8310d3d7bec28        refs/heads/3073-kschaaf-domif-perf
da74982f1cfa5adc781e0f0f4623eee18c7012f6        refs/heads/3073-kschaaf-domif-perf-bespoke
87004c901b4a35e6565fb725e91f24ec4b223d3c        refs/heads/3358-kaste-computed-bound-methods
a2b51de0d3dc3ff72f369009e310557cad7c8ea5        refs/heads/betterhelp
11c987b2eb3c73b388a79fc8aaea8ca01624f514        refs/heads/builds
c37abe5b0d4958b4bcc2b34f0870bbea93c35d43        refs/heads/dom-bind-defer
82588571883199311757faac98db8d9f43683dcc        refs/heads/enable-preventdefault-for-touch
c3cbde93e958f87b655d5a8a09c64383bba31e01        refs/heads/extends
a99f123021e2b94eb093355a60552cb57eb6cae4        refs/heads/extends-plus-set-object-array
c6bd1c899a073bc305487d0e1108f0f3a9f7f9fe        refs/heads/fix-2481
a1702613e5df177e5c18f994c7b280aad97d393b        refs/heads/gh-pages
13580f540cdebe6dcdbf4c9a04563db4e8ff6272        refs/heads/gh-pages-docs
2fcdd91fd997bf5f0f57545144410f88c9050130        refs/heads/lazy-register
1fd11bd0de918644d57a218f8150e7ade58023dd        refs/heads/lazy-register-extends
c0e0a73e31204e26374a46fce22ded71f0213578        refs/heads/master
2ad44de5f2672000f18f7ae3bae5593f34236a9b        refs/heads/media-queries
a5b19b755a40b4a198992dcd8e934e7cba02a98d        refs/heads/mixins-as-custom-properties
438208d41463653790b0069f30ee06ea16d228af        refs/heads/normalize-qs-undefined
54c0f3772c230f7d51983aafa4652e214d7962be        refs/heads/selectable-array-selector
ae5bbf9eb1cfa3f239996a827e69ee4f93f3ea00        refs/heads/set-object-array
f2909b42d5635fb2d4032fdda841e7755eab9b3d        refs/heads/shady-slot
b7348a2d8d6b241eeafe31b379782a7236151aaa        refs/heads/standard-layer
1baf96ffd94bceb8bb8b0270e2fded7286745ca0        refs/heads/was
b1a1c2f1213a9312709c00ef0ee04c97ab5d4966        refs/tags/0.1.0
a9e5f23ca0acc39e00eff7eb21b90b5e564ef1f4        refs/tags/0.1.1
29ba624844b6d6569bc3a303d8cda603310bb3c2        refs/tags/0.1.2
1879f0482e344e69a7e1c8267a44d98ec0fe8174        refs/tags/0.1.3
b7030d296c62fa0db0e011e6ad057c813bb92c16        refs/tags/0.1.4
ea02f956b31e8878abc9bcd8debe0e4f178a0d4b        refs/tags/0.2.0
62ec4216813ccd9344cf419da846b623892f0884        refs/tags/0.2.1
2121c9c6e399e2ea5f4156826bcb4f75f97354e1        refs/tags/0.2.2
a0632dc45fc02a60f70881f49a9d18d9987ea243        refs/tags/0.2.3
8564d0e7ce8d426e2492e7b69478d9feb62e20ef        refs/tags/0.2.4
129435c4095be31001507cc69b6dc9346cd19b06        refs/tags/0.3.0
24eb6673bd6597f46a7cd8e61eae0bd7912e8b69        refs/tags/0.3.1
435fc392dc8787cf6a724564b9154cc7170cadc5        refs/tags/0.3.2
4516bcea83b851f2bdb023111df71781483e6e71        refs/tags/0.3.3
49a331373b78e37b415dca8e360223b2f63c4035        refs/tags/0.3.4
a09a0e689fdeab11b53b41eaed033781733bf1eb        refs/tags/0.3.5
441a1bd4043387789f8f4be22cafdaadb8d2d860        refs/tags/0.3.6
9ba136949d4a3bbf5c30ab04d284a709d01b3100        refs/tags/0.4.0
c0c8865f5a8f51d48712621f222ac97f00427f66        refs/tags/0.4.1
90270bc3b8f1537b849ca1b1c0283a7c0691c0f7        refs/tags/0.4.2
1c75ff361e7881864205bdeaa56df02e994ce9f3        refs/tags/0.5.0
c654b2b4996a643e79234ac624d7bc38179dfc2c        refs/tags/0.5.1
2a9ca53fa79ca09907e818f1adf806765409ec9c        refs/tags/0.5.2
76b579af8ba514570964a5771be7aca06bad716d        refs/tags/0.5.3
4b730b4ed03cb8767fbd74385ebf1bf05f6e3b74        refs/tags/0.5.3-rc
19350f4725ebfbc3077c1f8314db2ef2fe40a1ee        refs/tags/0.5.3-rc2
17f0b5d75b1ceeb4414556d44eca197f7dacbde2        refs/tags/0.5.4
b94b680c966fc9ea86bc8f14b3af6f13d77f217a        refs/tags/0.5.5
94b1b78923cf3cb1881688171efc1dd990264054        refs/tags/0.5.5-rc1
bf567ab71feecd6e98adce658132c65ffbeb721f        refs/tags/0.5.6
0b8de695a1e515c5136eee8c477ce685407cba11        refs/tags/v0.0.20130711
9c8068f25dbe1cc218079dec1480a716b2f5e816        refs/tags/v0.0.20130801
12fb68a092a2a2167509108510f9bd14baba034d        refs/tags/v0.0.20130808
a32f21b234129a290ea4931a2c6d7345f6825789        refs/tags/v0.0.20130815
a32f21b234129a290ea4931a2c6d7345f6825789        refs/tags/v0.0.20130816
c8d5aa7d5622ad77919532d20924a4abc12c6d08        refs/tags/v0.0.20130829
c440c8e0ff032587ccf22860dcc20f1b9520bf1c        refs/tags/v0.0.20130905
90ecb3dafd95a92690bebd6d9c440efc4b534068        refs/tags/v0.0.20130912
0005280cf49ffa033f3c37cca9ea8e8158ada8be        refs/tags/v0.0.20131003
fe2ba2c3101dbf583c9540591758a82185475daa        refs/tags/v0.0.20131010
6fcff14beaa7e02bc5a1cabc78bc637897812e55        refs/tags/v0.0.20131025
7b138609bd363d65b8c2d1841e4afab4d5c4cff4        refs/tags/v0.0.20131107
2e954ab8bbbd4d7ef6fcb35863222f28161528e8        refs/tags/v0.8.0
6cc290156c0e44d98e5303fc627745f9d43d261e        refs/tags/v0.8.0^{}
58b72c9fee81b7f2483253c45d9e71ac8c985634        refs/tags/v0.8.0-rc.1
365edf4c1b1b62797269bf7b46f7f00e935a89df        refs/tags/v0.8.0-rc.1^{}
f1256268817204ef328ed1732b258968f53f16a5        refs/tags/v0.8.0-rc.2
9caf5fae29d421c0cea51182e86bcb7f61e33838        refs/tags/v0.8.0-rc.2^{}
f81ff70f8113490f211852481042872f2b8b7dbf        refs/tags/v0.8.0-rc.3
8b3e140d4a21bac26d23afbac2566525db916ab6        refs/tags/v0.8.0-rc.3^{}
ba0c926fa409dd9c9eed2a5a52b082f527548e77        refs/tags/v0.8.0-rc.4
5330526c7b3f18fe031757424e151334fa8cbbb9        refs/tags/v0.8.0-rc.5
b8bf35513a741709d8f9072e5f40d87aa77f90e9        refs/tags/v0.8.0-rc.5^{}
0afd08ab8616d09c35b9da0b5cf6a4215ad1e3d4        refs/tags/v0.8.0-rc.6
ce138bc0bb96c74421ba76bf3b5f1aa46b126569        refs/tags/v0.8.0-rc.7
4061137fee21071499cceecc63a7c6954bbabc2f        refs/tags/v0.9.0
0c26c328edb6da03fba645fb91d40eeb31e869bf        refs/tags/v0.9.0-rc.1
2b7f2456bd3ac47960d90937a48845a69fcf7ed1        refs/tags/v0.9.1
a8af216b01fad56df9e1f56b9c235ea24f33096b        refs/tags/v0.9.2
6cf096730f00c17ec494fa33e9f7e3ce90c17fb2        refs/tags/v0.9.3
7eaa010d31d8d8541a4d744784067742a7992fd1        refs/tags/v0.9.4
6deed349cf3790e0481a525cada3d1001cb36c84        refs/tags/v1.0.0
282a92f4c983f42d8948ed3a9383e816925c661f        refs/tags/v1.0.1
63f3bf1babfeaba5649345569b1bd9f3d61a88ae        refs/tags/v1.0.2
336178d90e44ea7e01ec84155e83d037adf05a4c        refs/tags/v1.0.3
cdabb91ad8ddf9bbefa308a25c5633d768501e7d        refs/tags/v1.0.4
b93f076d7b2606733d7166f311b77550deb98a39        refs/tags/v1.0.5
953fcba374812690c279abdacbfaf61e3e3aa347        refs/tags/v1.0.6
b39d0015ce5428232409eb3aca7ddefea899f894        refs/tags/v1.0.7
61968bc4e5db93e76306a13517014d4d3b787021        refs/tags/v1.0.8
8e894841ae36be85bade4b42f858ccb99b770e5d        refs/tags/v1.0.9
67fb2f85fd66d8556fc07cf1dec41ff5273fa68a        refs/tags/v1.1.0
c0bd5a73b4bd694b7fa5ead01ff558ed542f6bd8        refs/tags/v1.1.1
9b0a25e347404ac164bc610bbd2ccbc91b6799b2        refs/tags/v1.1.2
fb2b93bf2f5058027c63a50fda79b130388b6e15        refs/tags/v1.1.3
eaedcbc28671ee6cf6a4c0350133bdddfbff50b8        refs/tags/v1.1.4
4c94736fac6681e84ec8c00da53484c5d3c2226b        refs/tags/v1.1.5
84d211624cffd04d6894ec90713c2029732e8bb5        refs/tags/v1.2.0
be2d57a329244735ca7aac34ac56c96b6270ae79        refs/tags/v1.2.1
f7b07058659d691b4331c24e4f2134ed84892229        refs/tags/v1.2.2
aa535d1675342007cbf64dc9c66497cf74cbc616        refs/tags/v1.2.3
284332a905ddd60eab11901a82ac037976175cf8        refs/tags/v1.2.4
77504bc2092eed3ad631eff04b186b22e3affb6e        refs/tags/v1.3.0
61fac558012d9ef56ea78ed5435de0c418a4afbb        refs/tags/v1.3.1
11c987b2eb3c73b388a79fc8aaea8ca01624f514        refs/tags/v1.4.0

Anbu@hp-anbu MINGW64 /d/polymer/polymer-project
$

**Comment by maffoo** [comment]
I would suggest you take this up with the bower project. I don't have experience running any of this in mingw, but that might be part of the problem. I'm going to close this for now.

Not sure whether you're trying to do development, but if you just want to use the web interface you can download a pre-built package from bintray [here](https://bintray.com/labrad/generic/scalabrad-web/view).

**Comment by maffoo** [comment]
Closing since this seems to be a bower issue. @aanbuvenkatesh, please reopen if you continue having trouble with development.
