### ISSUE TITLE
Download link needed for pre-built binary package 

### ISSUE THREAD

**Issue by gregllong** [labrad/scalabrad-web#177]
Hi, 

I tried to follow instructions in the README.md to install and run scalabrad-web. I want to run the server in production mode, but I could not find a download link from https://bintray.com/labrad/generic/scalabrad-web. Would it be possible if someone could post a download link on the bintray? 

Thank you!

**Comment by jwenner** [comment]
@gregllong, please see the instructions I gave for accessing the latest version in #179. Note that you'll need a program (such as 7-Zip) which can extract .tar.gz files.

**Comment by gregllong** [comment]
Thank you! I should have looked for the file more carefully on that webpage.
