### ISSUE TITLE
Grapher: Allow for basic fitting

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#182]
The old Delphi grapher has support for fitting parabolas and exponentials. There are times when such manual fitting is useful. Note that it's possible that this might be implemented in a similar manner to #181, by doing the fitting and then using #181 to display the fit.

**Comment by joshm-3b6b58** [comment]
This is a good idea. The question is how do we want to support it? Do you want to add a list of fit functions and have them accessible by buttons somewhere a-la old grapher? Do we need to support any customizing fit functions?

**Comment by btchiaro** [comment]
I think it would be nice to have a button for the standard ones like
exponentials, but it would be nice to support arbitrary fit functions with
a text box or something.

**Comment by jwenner** [comment]
Perhaps it might be good to have buttons for the standard fit functions which then populate a text box used to define the fit function. That way, the parameter names are clearly defined, and it's possible to verify the fit function used (and modify it if necessary).

**Comment by joshm-3b6b58** [comment]
Can you enumerate the standard fit functions you'd like?

**Comment by jwenner** [comment]
For the standard functions, I would think at least exponential and parabola. This would at least maintain feature parity with the old Grapher. Beyond this, I could see linear, Gaussian, or sine, but I don't know how much we would want these (at least, assuming we can enter mathematical functions in a text box).

**Comment by jwenner** [comment]
By the way, I'd say this is only of medium priority. In particular, I'd say this is probably on the low end of achieving feature compatibility with the old grapher.

**Comment by adamcw** [comment]
I have begun work on this in a branch, at the moment the goal is just feature parity so I am porting Parabola and Exponential fits from the Delphi grapher only.

https://github.com/labrad/scalabrad-web/tree/182-basic-fit-functions

I looked into more generic fitting methods, and implementations in JavaScript are sparse, and ones with proper licensing were non-existent. They are sufficiently complex that I left fitting to a generic function as a task for the future based on demand.

The branch so far ports the basic fitting functionality, but has no UI to turn them on/off, nor does it display the coefficients of the fitted function anywhere. At the moment I am rendering fits in the same color as the line it is fitting, but twice the thickness. I figure this is appropriate given they will be toggled on and off by the user, so you will want them to be clearly seen, but also easily identifiable in terms of which trace they apply to.
