### ISSUE TITLE
make grapher faster for large datasets

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#185]
It really bogs down, esp in 2D. 

@maffoo is this a bug or an enhancement?

Others, are speed rendering issues hampering y'all?

**Comment by maffoo** [comment]
I would call this an enhancement, but it's definitely important to make things more usable for people.

**Comment by jwenner** [comment]
The rendering speed would be hampering me if I were primarily using the web grapher. But, I'm still primarily using the Delphi grapher.

> is this a bug or an enhancement?

Yes. (i.e., both)

**Comment by adamcw** [comment]
This is turning into a major rewrite/restructure of labrad-plot.ts. Keep this in mind if you decide to make changes to this file, as the resolution will be non-trivial.

**Comment by adamcw** [comment]
This issue will also resolve #208 by removing the need for a clipping plane at all.
