### ISSUE TITLE
User Interface Discussion

### ISSUE THREAD

**Issue by adamcw** [labrad/scalabrad-web#199]
There are a few open issues regarding the user interface when traversing the directory structure, which is fairly unintuitive as it stands.

https://github.com/labrad/scalabrad-web/issues/69
https://github.com/labrad/scalabrad-web/issues/72
https://github.com/labrad/scalabrad-web/issues/68

There are a few possibilities:
1. Make item click follow the item path, but have icons to the right hand side that lets you edit or delete that item. This would remove the need for "selecting".
2. Make the item click select the item, and have an icon to the right specifically for following the item path.
3. Use a right click context menu to hide away the edit/delete buttons entirely, and have left click follow through.
4. Have a single click select an item, and double click follow the item path.

I am personally a fan of option 1 or 2. I like the entire UI to be visible. I don't like "hidden" functionality, that relies on the user trying click, double click or right click. 

Given the mobile-esque theming of Polymer, the lists naturally afford a single click to follow through if anything, and do not immediately feel like folder on a desktop which would be required for 4 to feel natural.

Option 2 Is the only option that has no hidden UI elements, as well as allowing multiple selection. Unfortunately, multiple selection is itself a hidden feature. At which point you are mimicking a desktop filesystem GUI, and that brings Option 4 back into the mix.

I'm not 100% confident in any one choice, so I figured I'd open it up to the people using it day-to-day. What do you think would be the most natural way to handle this?

**Comment by joshm-3b6b58** [comment]
I like option 2 the best. In earlier revision had extra anchor icons for selecting or dragging or whatever. If you look at the behaviour in Google drive, that's kinda nice, flicking the icon is a drag target, but clicking anywhere else allows you to drag a square to multi-select. 

I think we should make it a goal to just emulate that since it will be familiar to everyone and is nice.
