### ISSUE TITLE
kick++ Technique.

### ISSUE THREAD

**Issue by adamcw** [labrad/scalabrad-web#207]
Can someone please explain what led to the use of this seeming hack? I am finding the data binding in Polymer quite frustrating when it seems things like this are necessary. Even using the proper Polymer array mutation methods don't seem to actually fire the correct events.

**Comment by maffoo** [comment]
I had problems getting the data binding in polymer to work well with lists, in particular when you have computed properties that depend on a list property. Using the polymer array mutation didn't seem to trigger the computed properties to be recomputed. By making the computed property also depend on the primitive-valued `kick` property and bumping its value, I could get the computed properties to update. It is indeed a hack to get around problems in the data binding implementation. I don't know the best way to fix this; it's possible that computed properties work right in newer versions of polymer and the hack can just be removed. It's also possible that this could be restructured to not rely on computed properties to pass info to the template and then again this hack would not be necessary. And finally, we might be able to ditch polymer templates and use something like react which doesn't use data binding but instead relies on explicit rerendering. I'd be open to any of these.

**Comment by joshm-3b6b58** [comment]
We can close this now, right?

**Comment by adamcw** [comment]
I left it open because I wanted to write some brief documentation on how the data binding works, but who knows when I'll get around to it. For now I'll just link to the relevant docs I found, and we'll close this up.

https://www.polymer-project.org/1.0/docs/devguide/data-binding#array-binding
https://www.polymer-project.org/1.0/docs/devguide/properties#array-observation
