### ISSUE TITLE
Zoomed plots render outside chart

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#208]
This is on current master.

Load a plot, looks like this:
![image](https://cloud.githubusercontent.com/assets/8173925/16426658/def8f896-3d1e-11e6-9421-217620ce8647.png)

Zoom into area of interest, plot renders outside the chart:
![image](https://cloud.githubusercontent.com/assets/8173925/16426682/f337f2c6-3d1e-11e6-8f4e-706f720f23ba.png)

**Comment by joshm-3b6b58** [comment]
Also happens when plots are dragged :(
![image](https://cloud.githubusercontent.com/assets/8173925/16426827/7edead60-3d1f-11e6-9609-0631eb98656a.png)

**Comment by joshm-3b6b58** [comment]
The code that should keep the graph from overflowing the chart is here: https://github.com/labrad/scalabrad-web/blob/master/client-js/app/elements/labrad-plot.ts#L379

**Comment by joshm-3b6b58** [comment]
Weirdly things render fine on the current version of matrix-reloaded.

I hope this doesn't have something to do with updating D3...

Edit: I reverted D3 to 3.5.6 on my machine and still see the issue

**Comment by adamcw** [comment]
This was a known bug before the updating of D3.

It it is fixed in my WebGL branch so I didn't bother making an issue for it, will be fixed once that gets through review.

(WebGL doesn't use a clipping frame at all, so this bug was basically fixed for free)

**Comment by joshm-3b6b58** [comment]
Well it doesn't happen in 7b4f8a67500 either, I'm trying to track down where it popped up
