### ISSUE TITLE
PR Pending Label

### ISSUE THREAD

**Issue by adamcw** [labrad/scalabrad-web#217]
I've created a `pr-pending` label that can be applied to issues that have a PR in queue that should resolve the issue.

I've found it helpful when resolving a bunch of issues for PE month, as it makes scanning the list of issues much easier and you can filter resolved branches out. It also lets anyone subscribed to the issue know that there is a PR available for them to checkout and perhaps review if they are willing/able.

I think this would be a good organisational feature into the future, but I'm opening this up as discussion if others think a better name would be suited, or there is already a way to indicate this I'm not aware of.

**Comment by maffoo** [comment]
If you create a PR and indicate in the description that it "Fixes #XXX" then github will show links in both directions (the PR links to the issue and vice versa). I tend to just use that, but I'm not sure that creating such a PR actively notifies people subscribed to the issue, so having a specific label might be a good idea. Of course, you still want the "Fixes" link so people who get a notification about the added label can look at the issue and find the right PR.

**Comment by adamcw** [comment]
I like the use of both, because I can't skim the list of issues and see what there is a PR pending for via the linking system alone.

I've also added an "under-development" label, which may be helpful to indicate that progress is actually being made on an issue. This makes it clear to everyone that someone has actually got an active branch on an issue, as it is currently unclear when issues are just assigned to investigate or have actual progress.
