### ISSUE TITLE
Issue Priority

### ISSUE THREAD

**Issue by adamcw** [labrad/scalabrad-web#218]
We have amassed quite a few feature requests, and it is difficult as someone who doesn't use this software personally day-to-day to know exactly what issues are the most pertinent.
## New Milestones

I have created two new milestones, v2.0 and v2.1.

Version 2.0 will be the first feature-parity version of Scalabrad-Web with the Delphi grapher and other available tools. I think we should move to getting feature parity ASAP.

Version 2.1 will be the first wave of super useful usability improvements taking Scalabrad-Web above and beyond what is currently possible, providing new features to aid in research.
## Features

If there is a missing feature, and no issue, please make it and mark it v2.0. If there are existing issues that are required for parity mark it v2.0.

If there is a feature that would make your day to day life significantly improved, mark it v2.1.
## Bugs

If there is a bug, or user interface issue that is significant such that it discourages you from using Scalabrad-Web mark it v2.0. 

If it is a problem, but easily worked around and mostly nicer to have, mark it v2.1.
### Thank You!

Your assistance in this would be greatly appreciated! Even just marking a few issues/bugs would be quite helpful.

**Comment by jwenner** [comment]
What is the relationship between "PE Fixits" and "v2.0"? Is one a subset of the other? It looks like any issue can only have one milestone.

**Comment by jwenner** [comment]
And should we have a milestone tag to indicate low priority (i.e., after v2.1)?

**Comment by adamcw** [comment]
PE Fixits is end-of-June goal thing, anything that is PE Fixit already, leave as is. ~~Those not completed will be modified to be v2.0, though I've been working on closing nearly all of them today.~~ (PE Fixit items will remain as such)

We are not creating new PE Fixits at this stage, mark appropriate issues as v2.0.
