### ISSUE TITLE
Convert remaining javascript files to typescript

### ISSUE THREAD

**Issue by maffoo** [labrad/scalabrad-web#220]
We still have a few polymer elements that include script tags containing plain javascript. Having this mix of languages can be confusing (see #211 for example). We should convert these to typescript.

**Comment by adamcw** [comment]
This probably needs to be done sooner rather than later. I've added it to the v2.0 timeline to avoid code health being deprioritized.

**Comment by adamcw** [comment]
@maffoo do you know off the top of your head the files that need to be converted? Or should I take an inventory?

**Comment by maffoo** [comment]
They're actually .html files with script tags inside. Look for .html files in the elements directory without a matching .ts file. That should be all.

**Comment by adamcw** [comment]
As far as I can tell we can delete:
- app/elements/dir-item.html
- app/elements/menu-button.html
- app/elements/expandable-input.html

But we need to convert:
- app/elements/selectable-table.html
- app/elements/labrad-setting.html
- app/elements/labrad-breadcrumbs.html

These are html files without ts files but don't have anything to convert:
- app/elements/elements.html
- app/elements/app-theme.html
