### ISSUE TITLE
Update version on matrix-reloaded

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#222]
It would be nice if the version on matrix-reloaded could be updated (likely once all the PE-fixit PRs have gone through) so that those of us at UCSB can make use of all the nice new features. Note that this may require an instruction guide (not in this repo) on how to deploy this on matrix-reloaded. Thanks!

**Comment by adamcw** [comment]
@maffoo You briefly mentioned you wanted to do better in terms of deployment process for Scalabrad-web.

As the software stabilizes, a rapid deployment process is probably unnecessary. It would probably be good to decentralize the update process though, and perhaps have an update script (or similar) that will pull the latest files from master, or preferably, from a provided tag. It would then be possible in the future to use Ansible to call this updater to allow for automated deployment whenever a new release is made.
