### ISSUE TITLE
Auto-scaling behavior when new points are added

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#231]
In looking at currently updating datasets with long time traces, I want to zoom into the latest time period and check on things. However, the plot autoscales as soon as a new point is added. 

Do we want this to be the default behavior? I figure it's always easy to get back to full scale with the home button, so autoscale show be disabled when you zoom or pan in any way, and re-enabled when you press the "home button"

How does that sound?

**Comment by adamcw** [comment]
The new WebGL branch should leave the zoom level as-is when new data is added if you have zoomed away from the home position. If that's not the case, then there is a bug.

**Comment by adamcw** [comment]
This has been added in #223, it wasn't working, but has been fixed.
