### ISSUE TITLE
1D Plot Live Limits

### ISSUE THREAD

**Issue by adamcw** [labrad/scalabrad-web#233]
Are the limits on the 1D plots in live view really the intended output? At least on the sample data you basically just see a flash of random lines. This is unlike the 2D limits which scale to fit all the data in the frame.

Is this a long standing bug, or does the non-test use case actually find this useful?

**Comment by maffoo** [comment]
No, this is not intended. The limits should work like for 2D plots, scaling to fit the full data set and adjusting as more data is received. I'm not sure when this broke.
