### ISSUE TITLE
Automatic zoom if only some dependent traces displayed

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#242]
For a 1D dataset with multiple dependent traces, the original y-axis limits are kept even if I select to display only some of the dependent traces. It would be nice if the y-axis limits were recomputed for only those traces being displayed. This is particularly useful when the difference between values between traces is much greater than the variation within a trace.

Note: currently on version 1.1.0-0: 280f46b

**Comment by adamcw** [comment]
If this is how it works in the Delphi grapher, this is a bug, otherwise it is a feature. Can you confirm?

**Comment by joshm-3b6b58** [comment]
This is a bug. Axes were recomputed after traces were changed on version before WebGL was implemented. This was just something that was missed on review.

**Comment by adamcw** [comment]
Ahh. The data generator doesn't really produce anything to test this functionality as it stands. I'll have to write a new case.

**Comment by joshm-3b6b58** [comment]
True story.

**Comment by adamcw** [comment]
The code that broke live streaming of 1D plots is the code that made the zoom level work when you change traces. Working on a way to make both work at the same time.

**Comment by adamcw** [comment]
A simple fix. Need to reset the data limits when redrawing the scene. Old code reset whenever `plot1DData` was called, which meant that the zoom was reset on every incoming live packet, but also worked when traces were modified. 

Since live data now doesn't redraw the whole scene, the reset can be put into `redrawScene` and avoid the live streaming issue.

**Comment by joshm-3b6b58** [comment]
So I recently had to get a new workstation, so my scalabrad-web stuff is kind of toast and I won't be able to get this to review for a day or two...

**Comment by adamcw** [comment]
Seems @maffoo is on the case!
