### ISSUE TITLE
Impossible to Edit Long Registry Keys

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#244]
#156 redux. For a registry key which is longer than the current screen size, the registry key flows past the end of the key edit box. When I try to drag value to see values currently off-screen, instead the main registry page scrolls. Note that I had shrunk the Chrome window size to test this. On version 280f46b.

![image](https://cloud.githubusercontent.com/assets/8183919/17120580/12ce3a28-5282-11e6-8af9-7012718e800a.png)

**Comment by adamcw** [comment]
The way this box resizes in general is a constant source of bugs and issues. I will look into trying to resolve this in a way that doesn't just cause more issues.

**Comment by adamcw** [comment]
This is due to a weird interplay of various Polymer components that weren't really anticipated by the authors, figured I'd update that work is in progress given this is taking longer than anticipated to resolve.
