### ISSUE TITLE
Expose "kill client" for manager browser

### ISSUE THREAD

**Issue by ejeffrey** [labrad/scalabrad-web#247]
It occasionally happens that a server is running outside of a node.  In that case, an updated copy of the server cannot be started unless the old one gets shut down.  The manager interface to the browser should allow you to kill connections so that you don't have to hunt them down manually

See https://github.com/labrad/scalabrad/issues/62

**Comment by adamcw** [comment]
From my understanding, this is a feature required for parity so I've marked it v2.0.
