### ISSUE TITLE
Application secret not so secret

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#26]
Should [this](https://github.com/labrad/scalabrad-web/blob/6d30720892289f4aa24f8aa224dd137e48cc11c2/server/src/main/resources/application.conf#L12) be in version control?

**Comment by maffoo** [comment]
The way this is typically done is to deploy the app on a server with a different config file that overrides this secret. So I think of this as the dev mode secret and it's not a problem to have it in version control.

(Also, this is used by play for things like encrypting session cookies, which we aren't using at all; this value actually does not get used at all by the server here...)

**Comment by DanielSank** [comment]
Does deploying without writing an override config work? If so that seems kind of dangerous.

**Comment by DanielSank** [comment]
bump

**Comment by adamcw** [comment]
@maffoo Can you respond to this so we can either action or close it?

**Comment by maffoo** [comment]
`application.conf` is no longer needed since play framework is gone. We should delete it along with the `routes` file.
