### ISSUE TITLE
Make it possible to edit the registry with the keyboard only

### ISSUE THREAD

**Issue by maffoo** [labrad/scalabrad-web#272]
Using the registry editor currently requires a lot of mousing around. It would be very nice to make it possible to use the keyboard. Here is a minimal set of keyboard controllability I'd like to add:
1. Use up and down arrow keys to highlight an item in the list.
2. Press `enter` to navigate into the highlighted directory (or up a level) or to edit the highlighted key.
3. When the edit box pops up, the edit area displaying the value should be focused so user can just start typing.
4. Press `shift+enter` to keep the edited value. It should also be possible to press `shift+enter` from the value edit area when creating a new key.

As part of this keyboard control, we should ensure that tab order works in a sensible way with the various dialog boxes, so that the user can tab between text fields and dialog buttons to control the dialogs. I think this _sort of_ works, but we should just try it out systematically.

Regarding number 1 above, we also have a filter box to restrict the set of keys that are shown. It would be good if this box could interact nicely with other keyboard controls so that it can be used without clicking on the box and then back on the list to select something. For example, pressing up arrow when the first element in the registry listing is highlighted could move the focus to the filter box; pressing down arrow from there would again highlight the first item in the listing. Alternately, we could just capture keystrokes other than up/down arrow and enter and use them to modify the filter text _as if_ those characters were typed in the box. I'm not sure the best thing to do here, so some experimentation is in order.

**Comment by adamcw** [comment]
As of #279 all tab ordering for the dialogs in the registry are correct.
