### ISSUE TITLE
Package some stuff as independent lib

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#3]
Seems to me a lot of what's in client-js isn't particularly tightly coupled with LabRAD. Any plans to package independently?

**Comment by maffoo** [comment]
no plans, but certainly possible. Do you mean like the basic framework of having a project set up with npm, bower, gulp, etc.?

**Comment by DanielSank** [comment]
That and the rpc stuff.

**Comment by maffoo** [comment]
I'm going to close this for now. Let's focus on getting things working before we think about splitting pieces out and packaging them separately. Packaging and distribution is not trivial (we have to figure out how to distribute npm packages containing typescript code, etc. etc.), and we should not get too distracted.
