### ISSUE TITLE
graphs are empty with chrome remote desktop

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#317]
I was checking a dataset from home using Chrome Remote desktop, but the plots are empty. Here's an example:
![image](https://cloud.githubusercontent.com/assets/8173925/20375786/4b2c8646-ac36-11e6-8e07-beba00fcb62a.png)

**Comment by maffoo** [comment]
webgl is not enabled by default when using remote desktop. We've had this issue before but I can't find it at the moment. See your comment on #241 for a possible resolution.

**Comment by joshm-3b6b58** [comment]
Oh yeah,I remember now. Closing
