### ISSUE TITLE
Ctrl-click on intra-app links does not work properly

### ISSUE THREAD

**Issue by maffoo** [labrad/scalabrad-web#33]
For app-links, Ctrl-clicking just follows the link, whereas it should open the link in a new tab and leave do nothing in the current tab (just like conventional links). The links in the menu tray also do not handle Ctrl-click properly; in that case the link is opened in a new tab as expected, but the current tab also gets messed up (it seems to update the ui as though it were making a screen transition, but does not actually update the page url).

**Comment by joshm-3b6b58** [comment]
So, in looking at existing [Polymer projects](https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/app-shell/app-shell.html) from Google, the way that they handle this is to use the [app-router](https://github.com/erikringsmuth/app-router) web component. 

I don't know if this also is related to the life-cycle of the components conversation I had with you (briefly) on Friday, so I don't know if adding this is a good idea or if it would conflict with the refactor already in progress.

**Comment by joshm-3b6b58** [comment]
Nevermind, can simply be fixed by stealing this code: 

https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/app-link/app-link.html

**Comment by maffoo** [comment]
Funny that we picked the same name `app-link` for this component. Thanks for the tip about the `app-router` component. That's certainly something we can try out.

**Comment by joshm-3b6b58** [comment]
This should probably be re-opened since the lifecycle issue isn't fixed.

**Comment by joshm-3b6b58** [comment]
I'm closing this since https://github.com/labrad/scalabrad-web/pull/49 fixes this
