### ISSUE TITLE
LabRAD registry doesn't show all items

### ISSUE THREAD

**Issue by fanmingyu212** [labrad/scalabrad-web#330]
When the registry folder contains more than 40 items, the extra items are shown as blank space in the web manager.

How to reproduce:
 - Create a new folder in the registry, and name it (e.g. "test").
 - Create new keys with names from "01" to "41".
 - Only "01" to "40" are visible. After refreshing the web page, the position that should show "41" is shown as blank space.

It would be appreciated if someone can point to me how to solve the issue.

**Comment by maffoo** [comment]
As a workaround, you should be able to resize the browser window and the additional list elements should appear. There's actually a very simple CSS fix for this issue that we can add. Are you using binary packages from bintray to run the web interface or compiling it yourself?

**Comment by fanmingyu212** [comment]
@maffoo thank you for the reply. The workaround works for us!

We are using the binary package but we can compile by ourselves. It would be much appreciated if you can release a newer version to bintray.

**Comment by fanmingyu212** [comment]
@maffoo thank you very much for fixing this issue!

**Comment by maffoo** [comment]
Released version 2.0.6 with this fix: https://bintray.com/beta/#/labrad/generic/scalabrad-web/2.0.6
