### ISSUE TITLE
Floating buttons on registry ui cover the navigation menu

### ISSUE THREAD

**Issue by maffoo** [labrad/scalabrad-web#34]
The floating toolbar buttons on the registry editor ui cover the navigation menu which slides in from the left; this makes it hard to navigate from the registry editor to other parts of the site.

**Comment by joshmutus** [comment]
Do you mean the drawer-panel? That doesn't happen for me.
![image](https://cloud.githubusercontent.com/assets/8173925/9266519/fa278a98-41f6-11e5-9889-1b145f29c71e.png)

**Comment by joshm-3b6b58** [comment]
I don't think that happens for me:

![image](https://cloud.githubusercontent.com/assets/8173925/9266528/2b5c54b8-41f7-11e5-82f2-4e19ab1ca043.png)

**Comment by maffoo** [comment]
Here's what it looks like for me on linux (chrome 44.0.2403.155 (64-bit)):
![screenshot from 2015-08-14 08 18 33](https://cloud.githubusercontent.com/assets/129268/9277285/ecb96220-425d-11e5-97ae-921362f7d042.png)

**Comment by maffoo** [comment]
yay browser differences!

**Comment by maffoo** [comment]
Same thing in chrome on mac.

**Comment by joshm-3b6b58** [comment]
Oh, noes! I restarted my workstation and this is happening to me!
