### ISSUE TITLE
weird things happen when I pass a large int to "org.labrad.registry.set"

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#36]
When I pass a large integer like 30716360112 the registry key gets set to 651589040. Works for smaller integers or floating points. Not sure where the problem is.

Also, not sure if this is an actual problem (probably never need numbers this big). I only broke it when trying to test random inputs for my new fangled expandable input component. Probably should return an error though.

**Comment by maffoo** [comment]
30716360112 is not a valid labrad integer because it doesn't find in 32 bits. It overflows to the value you're seeing:

``` python
>>> 30716360112 & 0xFFFFFFFF
651589040
```

I've filed an issue with scalabrad to fix this.

**Comment by adamcw** [comment]
Closing this since it sounds like there is nothing to be done in Scalabrad-web to fix it.
