### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#4]
I'm working on a branch to try and figure something out and I'm trying to push it so I can get some help, but I can't 

```
remote: Permission to labrad/scalabrad-web.git denied to joshmutus.
fatal: unable to access 'https://github.com/labrad/scalabrad-web.git/': The requested URL returned error: 403
```

**Comment by maffoo** [comment]
added @joshmutus to the labrad org. can you confirm that you have access and then close this issue?

**Comment by joshm-3b6b58** [comment]
Yup, it worked!
