### ISSUE TITLE
When is this going to be released?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#40]
I could be totally out of whack here since I'm not working on the code myself, but I feel like all the little details being worked on shouldn't prevent this stuff from being used.

**Comment by maffoo** [comment]
I agree that we'll get a better sense of what needs to be worked on by having people actually use it. Of course there's nothing stopping anyone from doing that right now, but we haven't made it easy for a peripherally interested party to do so. I'll work on that.

**Comment by maffoo** [comment]
So, short answer: soon.

**Comment by DanielSank** [comment]
I also kind of think that if others start using it you guys won't be so tied up dealing with little UI niceties :-)
