### ISSUE TITLE
How do I use the new registry editor and grapher?

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#43]
I'd like to use the new registry editor and grapher ASAP. How to do?

**Comment by DanielSank** [comment]
I need to be pushy about this. I'm having weird issues with running the registry editor through Wine. Anyone? @joshmutus @maffoo?

**Comment by maffoo** [comment]
@DanielSank, the easiest thing for now is going to be to just run the server locally (checkout this repo and follow the instructions in the [README](https://github.com/labrad/scalabrad-web/blob/master/README.md). You'll need node.js, which I'm happy to help you get working if you need anything. When things stabilize a bit, I will feel more comfortable publishing pre-built jars for people to download without requiring node.js for development.

**Comment by DanielSank** [comment]
Groovy.

**Comment by joshm-3b6b58** [comment]
Yeah, sorry for not replying. I haven't had time lately to put on this and
I have two PRs rotting because I haven't made simple changes :(

**Comment by DanielSank** [comment]
It works by following the instructions in the readme, so closing.
