### ISSUE TITLE
Binary package availability

### ISSUE THREAD

**Issue by ejeffrey** [labrad/scalabrad-web#53]
Is needed

**Comment by DanielSank** [comment]
+1 Currently trying to run from source. Would be nice to not have to.

**Comment by creilly** [comment]
Would like this as well. On this github page there are a few mentions of a production mode for this application but the README as far as I can tell gives only directions for running the development version.

**Comment by maffoo** [comment]
Packages are now being published on bintray: https://bintray.com/labrad/generic/scalabrad-web/view

There's a reasonable amount of development going on, so I hope we can have an official 1.0 soon.
