### ISSUE TITLE
Explain how the server and client webserver work

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#54]
Something in the readme should be added to explain why 2 servers need to be running for the app to work.

**Comment by DanielSank** [comment]
+1

Diagrams are helpful for this.

**Comment by maffoo** [comment]
It's only needed for development, and even then only if you want live-reloading of the client code. But yes, this can all be explained in the doc.

**Comment by DanielSank** [comment]
Which one is only needed in development?

**Comment by maffoo** [comment]
The node.js server is only needed for developing the js front-end code with live reloading. In production,  the scala backend server takes care of serving the static files that were compiled for the frontend (javascript, css, html), so that one server is all that's needed.

**Comment by joshm-3b6b58** [comment]
So what port do we connect to on the production server?  Where is the websocket server in production? I guess I never knew it was that different

**Comment by maffoo** [comment]
If you produce a binary package and run it, it's configured to listen on port 7667, just like the old java web gui.

**Comment by DanielSank** [comment]
@joshmutus I think you can see this in the gulp config file.

**Comment by maffoo** [comment]
This is now explained in the README file.
