### ISSUE TITLE
Add indication of pending operations

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#55]
In the registry editor, if copying a large directory which takes a long time, there's no indication that the copy is pending.

**Comment by DanielSank** [comment]
Bump. This cases all kinds of annoying a subtle problems. It seems that if I try to do something before a long registry copy operation completes, the copy misses random keys. I'm not sure that's what's really going on yet, but it seems so.

**Comment by joshm-3b6b58** [comment]
I'll take a look at this in the morning.
