### ISSUE TITLE
Startup time really slow

### ISSUE THREAD

**Issue by ejeffrey** [labrad/scalabrad-web#59]
Web server takes over 100 seconds to start up, enough that I thought it was broken.  Is this normal?

**Comment by maffoo** [comment]
No, I've never seen it take that long. On my mac laptop it takes less than a second. Can you provide any more info?

**Comment by ejeffrey** [comment]
It happens before producing any output (the first line of output is about
logger configuration being deprecated).  I looked in 'top' and it looks
like it isn't using a lot of CPU, sometimes zero and sometimes 5-10%.

I just tried running it on one of our workstations, and it works fine, so
this is probably an issue because I am running it on the manager with no
internet access.  Maybe a timeout of something?

**Comment by maffoo** [comment]
I don't know of anything that would be timing out, but it's possible. How long does java take to start up on that machine? Is the manager similarly slow to start?

**Comment by ejeffrey** [comment]
The manager takes about 40 seconds.  Java itself is fast to start up if I run the old java browser it starts immediately.

**Comment by maffoo** [comment]
Last I heard we suspected this was due to DNS resolution failing. @ejeffrey, is this still a problem?

**Comment by maffoo** [comment]
Closing after discussion with @ejeffrey.
