### ISSUE TITLE
redundant dependencies in client-js

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#6]
In `client-js` when I do the `$ npm install` step I see a warning

> Dependency 'node-libs-browser' exists in both dependencies and devDependencies, using 'node-libs-browser@^0.5.2' from dependencies

Does this mean the dependencies need a little housekeeping?

**Comment by maffoo** [comment]
The dependencies almost certainly could use some housekeeping; we're all n00bs when it comes to `npm` and friends. Feel free to submit a PR. Please be sure to test that a clean checkout and install (according to instructions in the readme) works.
