### ISSUE TITLE
Registry editor doesn't work, provides no feedback.

### ISSUE THREAD

**Issue by ejeffrey** [labrad/scalabrad-web#60]
When I modify a registry value, it shows up as changed, when I navigate to a different folder and back, the change disappears.

**Comment by maffoo** [comment]
Are you pressing shift+enter to actually submit the changes? And yes, clearly we need some work on the UI...

**Comment by ejeffrey** [comment]
Ok, yeah.  that works.  In this UI I expect when I click away from the text
field and it reverts to "non-edit mode" that it will save the changes.
Failing that, I would expect an "apply button", and failing that, I would
expect that navigating away would generate a warning that there are unsaved
changes.

**Comment by joshm-3b6b58** [comment]
Yeah, this process has to be made more clear. There's a little tooltip to say "shift+enter to submit" did that show up?

**Comment by ejeffrey** [comment]
Yes, I see the tooltip.  I didn't notice it because it only appears when the value is selected for editing and you mouse over the active value.  The first thing I did after clicking is move my mouse away so the cursor wouldn't obstruct the text I was trying to type.

**Comment by joshm-3b6b58** [comment]
The crux of the issue is that when focus is left from the paper-text area it appears that the key is changed when it is not. Maybe we have a popup dialog when leaving focus from input asking if the user wants to submit the edited key?
