### ISSUE TITLE
Remove playframework

### ISSUE THREAD

**Issue by maffoo** [labrad/scalabrad-web#64]
This is related to #58 (and possibly #59). The playframework currently determines how the server code is packaged and run, and the way it does this is different from our other scala binaries like the manager and various servers. If we use a different web server library then we can have more control over how this works.

Currently we do not use much in the way of play-specific functionality. The server just serves some static files (produced by the node.js-based build in `client-js`) and provides api connections over websockets. The websocket layer is play-agnostic with just a small shim in `BrowserController.scala` to adapt it to the way play handles websockets, so it should be fairly easy to swap in a different web server library.

The logical choice here would be [netty](http://netty.io/), which we already are using in scalabrad and which is also used in gRPC, among many other projects.

**Comment by maffoo** [comment]
Another advantage of ditching play: it is currently the only thing we have that _requires_ java 8.

**Comment by joshm-3b6b58** [comment]
Isn't this done?
