### ISSUE TITLE
Selecting text operation is cancelled by 'activate'

### ISSUE THREAD

**Issue by ejeffrey** [labrad/scalabrad-web#68]
If I want to select the text of a registry value, I click-and-drag, and the text highlights.  Once I release the mouse, the field becomes editable and my selection is cancelled.  The selection should be preserved.

**Comment by adamcw** [comment]
Editing a registry entry now requires a double click to activate, so I'm going to assume this problem is resolved. Please reopen the issue if it is still a problem.
