### ISSUE TITLE
prevent from copying directories into themselves

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#73]
Being able to copy a directory itself makes a very deep recursive structure of directories containing itself. 

My head hurts even trying to describe the issue.

**Comment by DanielSank** [comment]
Try this

``` python
d = {}
d['self'] = d
```

**Comment by joshm-3b6b58** [comment]
<img width="309" alt="screen shot 2015-09-30 at 8 59 00 pm" src="https://cloud.githubusercontent.com/assets/8173925/10212577/25aa2240-67b6-11e5-976f-09355fbbf2cd.png">![headesplode](https://media.giphy.com/media/EldfH1VJdbrwY/giphy.gif)

**Comment by DanielSank** [comment]
LOL

This is hilarious. I wasn't even thinking about js when I wrote that.
