### ISSUE TITLE
Registry editor should receive updates when key values change

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#84]

**Comment by joshm-3b6b58** [comment]
@maffoo so the plumbing looks like it's mostly in place for the RPC, we can set it to watch a path when the path is loaded in the browser. The thing I'm confused about is that when a subscribed event is received it just logs it to the console. Did you have any ideas about how to wire this up? We could fire an event, but the RPC isn't affiliated with any DOM element. Should we use the machinery in `observable.ts`?

**Comment by maffoo** [comment]
Yeah, we should add `Observable`s in `registry.ts`, then add listeners in the registry element. If you want to take a crack at this, you can take a look at the way the node does it for an example. I've got some changes coming with the grapher ui that should clean things up quite a bit, but for now we could set it up like the node controller.

**Comment by joshm-3b6b58** [comment]
Cool, I'd like to take a crack at it. That'll make me understand how the `Obervable`s actually work.
