### ISSUE TITLE
logging in through laptop

### ISSUE THREAD

**Issue by joshm-3b6b58** [labrad/scalabrad-web#85]
So I'm trying to log into the server run on my workstation from my laptop. I can't manage to log in. The page will render and the login dialog will show up, but I can't enter my password

The console on my laptop says ws://localhost:9000 connection refused. Is that web socket address hard coded in developer mode? Is the only way to run developer mode to run the client and server on the same machine?

**Comment by maffoo** [comment]
You can change the `window.apiHost` that gets set in dev mode to be a name that can be resolved from your laptop (e.g. `my.workstation.com:9000`): https://github.com/labrad/scalabrad-web/blob/master/client-js/gulpfile.js#L185

We could maybe modify the script to allow overriding this with a command line parameter or environment variable.

**Comment by joshm-3b6b58** [comment]
Great, thank you.

I think it's fine the way it is, I just didn't know where it was hard coded.
