### ISSUE TITLE
Improve zooming behavior in grapher interface

### ISSUE THREAD

**Issue by maffoo** [labrad/scalabrad-web#89]
A few improvements to the zooming behavior that we'd like to implement:
- zoom to box that user drags with mouse (like current grapher)
- when zoomed in or panned, don't autoscale as new data points come in
- after zooming, add a way to get back to "home view" that shows entire data set (and does autoscaling as new data points come in)

Assigning to @ccwa for her first contribution!

**Comment by joshm-3b6b58** [comment]
Welcome @ccwa! Where are you joining us from?

**Comment by ccwa** [comment]
Thanks, @joshmutus, I am based in MTV.

@maffoo, I have addressed all your comments, pls take a look when you have time. I probably can squeeze more time in the coming weeks, so feel free to assign more grapher related issue to me.

**Comment by jwenner** [comment]
@maffoo, can we now close this with #101 merged in?

**Comment by maffoo** [comment]
closed by #101

**Comment by joshm-3b6b58** [comment]
This was still open, so I closed it
