### ISSUE TITLE
Unable to log in while in development mode (Windows)

### ISSUE THREAD

**Issue by jwenner** [labrad/scalabrad-web#92]
When I enter the password & click LOGIN, I'm unable to actually log in (i.e., I get right back to the login screen). The message `[Object error]` is displayed above LOGIN. True both on remote computers and on local computer (using localhost:3000).

Running in development mode (as -M2 not available in bintray) on a Windows 7 computer using Node.js V5.0. Had to make the change in gulpfile.js as indicated in #48.

Also tried version -M1 in development mode & same problem. However, able to log in using -M1 from bintray.

**Comment by maffoo** [comment]
Do you have the backend server running locally? Do any error messages appear in the console window for the backend server?

**Comment by maffoo** [comment]
Also, I pushed a package for 1.0.0-M2 to bintray; I guess I had forgotten to actually upload the package after creating the version. Sorry about that.

**Comment by jwenner** [comment]
By backend server, do you mean the window where I run the commands (e.g., npm install, gulp serve)? If so, I can try to include the full installation messages below. Note that I have to run all this in Git Bash as jspm, bower require git.

If you were instead asking about during operation when I try to log in, I don't actually see any resulting error messages in the window.

**Comment by maffoo** [comment]
By backend server I mean the `sbt server/run` command mentioned in the readme. In development mode you have to run both the backend scala server (via sbt) and the frontend js server (via gulp).

**Comment by jwenner** [comment]
I hadn't seen that running a server was necessary. Thanks. Will take a look.

**Comment by joshm-3b6b58** [comment]
Let us know if you think the readme should be improved with better setup instructions.

**Comment by DanielSank** [comment]
> <s>Let us know if you think</s> Feel free to fix the readme <s>should be improved</s> with better setup instructions.

FTFY.

**Comment by joshm-3b6b58** [comment]
Closing this as we're not really supporting development mode on windows.
