### ISSUE TITLE
Key edit box is way too small

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#97]
It's so small that you often can't see the thing you're trying to edit.

**Comment by joshm-3b6b58** [comment]
Do you mind taking a screenshot? I noticed a wierd bug where the dialog will resize itself to uselessly small area. Is that it? Or is it normally just too short for typical registry keys?

**Comment by DanielSank** [comment]
This is what happens when I double click a key

![registry](https://cloud.githubusercontent.com/assets/4584456/11166215/39610cca-8ae0-11e5-8aa8-f11c68f20fff.png)

and here's what happens if I roll my mouse wheel upwards after the double click

![registry](https://cloud.githubusercontent.com/assets/4584456/11166222/5f3aa8e8-8ae0-11e5-8aed-4522c02e90e3.png)

Various riffs on this kind of problem show up pretty often. Perhaps the window size ought to be computed based on the length of the key?

**Comment by joshm-3b6b58** [comment]
Can you try restarting chrome, like really killing it, and checking if the
dialog is still tiny? I've had this issue intermittently as well.

**Comment by joshm-3b6b58** [comment]
So this is how I see it (I'm just curious if it has _ever_ showed up like this) : 
<img width="1364" alt="screen shot 2015-11-15 at 2 10 04 pm" src="https://cloud.githubusercontent.com/assets/8173925/11171357/e663ac1c-8ba2-11e5-8d05-496c86e2f3be.png">

**Comment by joshm-3b6b58** [comment]
I've asked the Polymer folks on the inside if they have any idea what's up with this.

**Comment by joshm-3b6b58** [comment]
So some of the dialog code has been updated, I'm interested to know if this still happens on version 1.0.1

**Comment by joshm-3b6b58** [comment]
Has anyone seen this problem since 1.0.1 was released? @maffoo @jwenner @julianskelly @DanielSank

**Comment by jwenner** [comment]
I don't see this problem on whatever version is on matrix-reloaded (as viewed on a Windows computer).

**Comment by jwenner** [comment]
But it appears that I do see the problem of #156. So, I don't know what version is on matrix-reloaded.

**Comment by adamcw** [comment]
With https://github.com/labrad/scalabrad-web/issues/156 resolved, can this issue also be closed? @DanielSank

**Comment by adamcw** [comment]
I'm closing this. If it is still a problem, please reopen it.
