### ISSUE TITLE
Use spaces after commas

### ISSUE THREAD

**Issue by DanielSank** [labrad/scalabrad-web#99]
The registry displays labrad arrays like this

`[56.234,31.56]`

whereas there should be a space after each comma, like this

`[56.234, 31.56]`.

**Comment by joshm-3b6b58** [comment]
Good idea. @maffoo should this be handled on the server side, rather than the client?

**Comment by maffoo** [comment]
see labrad/scalabrad#48

**Comment by jwenner** [comment]
Close?

**Comment by DanielSank** [comment]
I guess? The PR linked by @maffoo's comment has no changes in it so it's hard to tell whether this actually happened.

**Comment by maffoo** [comment]
I think I forgot to force push the branch before merging on that PR. The commit is in master: https://github.com/labrad/scalabrad/commit/e0af8318754e8ce6536e0e6c604509fcef5da234
